services:
  users:
    container_name: save-doc-user 
    env_file:
      - .env
    build: .
      # context: .
      # dockerfile: Dockerfile
    volumes:
      - './src:/opt/code/src'
    ports:
      - "8000:5000"
    environment:
      - FLASK_APP=src/apps/__init__.py
    