services:
  users:
    container_name: save-doc-user 
    env_file:
      - .env.prod
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    expose:
      - 5000
    volumes:
      - './src:/opt/code/src'
    environment:
      - FLASK_APP=src/apps/__init__.py
    depends_on:
      - users-db 
    links:
      - users-db
    
  users-test:
    container_name: users-test
    env_file:
      - .env.test
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    volumes:
      - './src:/opt/code/src'
      - './pytest.ini:/opt/code/pytest.ini'
    entrypoint: pytest 
    depends_on:
      - users-db 
    links:
      - users-db

  users-db:
    container_name: users-db 
    env_file:
      - .db.env
    build:
      context: ./docker/db
      dockerfile: Dockerfile
    ports:
      - 5432:5432

  nginx:
    container_name: nginx 
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    restart: always
    ports:
      - 8000:80
    depends_on:
      - users

  adminer:
    # image for a database server like PGAdmin
    image: adminer
    ports:
      - 8081:8080
    

    